/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.3-16-g4047a3bcd6"
#endif /* AVUTIL_FFVERSION_H */
